toruuu/config/routes.rb
Rails.application.routes.draw do
  resources :pr_videos

  devise_for :users, :controllers => {
  :registrations => "users/registrations",
  :omniauth_callbacks => "users/omniauth_callbacks" 
}
  root 'pr_videos#index'

end

toruuu/app/models/article.rb
class Article
  include Mongoid::Document

  

  field :title, type: String
  field :video, type: String

  mount_uploader :video, VideoUploader
  validates :title, :video, :presence => true
end

toruuu/app/models/pr_video.rb
class PrVideo < ActiveRecord::Base
	mount_uploader :video, PrVideoUploader

	validates :title, :video, :presence => true
end

toruuu/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,:omniauthable,:registerable,
         :recoverable, :rememberable, :trackable, :validatable



  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:     auth.extra.raw_info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    User.dummy_email(auth),
                         password: Devise.friendly_token[0,20]
                        )
    end
    user
  end


   def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end


  # 通常サインアップ時のuid用、Twitter OAuth認証時のemail用にuuidな文字列を生成
  def self.create_unique_string
    SecureRandom.uuid
  end
end

toruuu/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      devise_parameter_sanitizer.for(:sign_up) << :phonetic
      devise_parameter_sanitizer.for(:sign_up) << :age
    end
end

toruuu/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @articles = Article.all
    respond_with(@articles)
  end

  def show
    respond_with(@article)
  end

  def new
    @article = Article.new
    respond_with(@article)
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.save
    respond_with(@article)
  end

  # def update
  #   @article.update(article_params)
  #   respond_with(@article)
  # end
  def update
  respond_to do |format|
    if @article.update(article_params) && @article.video.recreate_versions!
      format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      format.json { head :no_content }
    else
      format.html { render action: 'edit' }
      format.json { render json: @article.errors, status: :unprocessable_entity }
    end
  end
end

  def destroy
    @article.destroy
    respond_with(@article)
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :video)
    end
end

toruuu/app/controllers/chat_controller.rb
class ChatController < ApplicationController
	def index
		render 'chat/index'
	end

	
end

toruuu/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
 # ユーザがログインしていないと"show"にアクセスできない
  before_action :authenticate_user!, only: :index

  def index
  end
end

toruuu/app/controllers/pr_videos_controller.rb
class PrVideosController < ApplicationController
  before_action :set_pr_video, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @pr_videos = PrVideo.all
    respond_with(@pr_videos)
  end

  def show
    respond_with(@pr_video)
  end

  def new
    @pr_video = PrVideo.new
    respond_with(@pr_video)
  end

  def edit
  end

  def create
    @pr_video = PrVideo.new(pr_video_params)
    @pr_video.save
    respond_with(@pr_video)
  end

  # def update
  #   @pr_video.update(pr_video_params)
  #   respond_with(@pr_video)
  # end
  def update
  respond_to do |format|
    if @article.update(article_params) && @article.video.recreate_versions!
      format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      format.json { head :no_content }
    else
      format.html { render action: 'edit' }
      format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pr_video.destroy
    respond_with(@pr_video)
  end

  private
    def set_pr_video
      @pr_video = PrVideo.find(params[:id])
    end

    def pr_video_params
      params.require(:pr_video).permit(:title, :video, :description)
    end
end

toruuu/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
 
  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

toruuu/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_action :configure_permitted_parameters, only: [:update]

  private 
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name,:phonetic,:age,:email, :password, :password_confirmation, :current_password)
    end
  end  


  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
 
end

toruuu/app/helpers/application_helper.rb
module ApplicationHelper
end

toruuu/app/helpers/articles_helper.rb
module ArticlesHelper
end

toruuu/app/helpers/chat_helper.rb
module ChatHelper
end

toruuu/app/helpers/dashboard_helper.rb
module DashboardHelper
end

toruuu/app/helpers/pr_videos_helper.rb
module PrVideosHelper
end

toruuu/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
  <%= f.label :video %><br>
  <%= f.file_field :video, :accept => 'video/*' %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

toruuu/app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

toruuu/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.video %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

toruuu/app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

toruuu/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<!-- <p>
  <strong>Video:</strong>
  <%= @article.video %>
</p> -->

<p>
  <strong>Video:</strong>
</p>
<p>
  <%= link_to @article.video_url.to_s do %>
      <%= image_tag(@article.video_url(:screenshot).to_s, id: "video", :alt => "screenshot") %>
  <% end %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

toruuu/app/views/chat/index.html.erb
<meta charset="UTF-8">
   <title>チャットしようぜ</title>
   <%= javascript_include_tag "application" %>
   <%= javascript_include_tag "chat" %>
 </head>
 <body>
   <h1>Chat Sample</h1>
   <div>ようこそ、<%= @current_user.name %>さん</div>
 
   <!-- jsに食わせたい情報などなど -->
   <div id="username" style="display:none;"><%= @current_user.name %></div>
 
   <!-- チャットのタイムラインとかテキストボックスとか -->
   <div id="timeline" style="margin:20px;">
     <div id="chat" data-uri="<%= request.host %>:3001/websocket"></div>
   </div>
 
   <hr/>
   <div>
    <form class="form-horizontal">
      <input type="text" class="form-control" id="msgbody" />
      <input type="button" class="btn btn-primary" id="send" value="送信"/>
    </form>
   </div>
 </body>

toruuu/app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

<% if user_signed_in? %>
<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "ログイン", new_user_session_path %>
<% end %>

toruuu/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Toruuu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
こんにちは <strong><%= current_user.name %></strong>.
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
<% end %>

<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

toruuu/app/views/pr_videos/_form.html.erb
<%= form_for(@pr_video) do |f| %>
  <% if @pr_video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pr_video.errors.count, "error") %> prohibited this pr_video from being saved:</h2>

      <ul>
      <% @pr_video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :video %><br>
    <%= f.file_field :video, :accept => 'video/*' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

toruuu/app/views/pr_videos/edit.html.erb
<h1>Editing pr_video</h1>

<%= render 'form' %>

<%= link_to 'Show', @pr_video %> |
<%= link_to 'Back', pr_videos_path %>

toruuu/app/views/pr_videos/index.html.erb
<h1>Listing pr_videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Video</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pr_videos.each do |pr_video| %>
      <tr>
        <td><%= pr_video.title %></td>
        <td><%= pr_video.video %></td>
        <td><%= pr_video.description %></td>
        <td><%= link_to 'Show', pr_video %></td>
        <td><%= link_to 'Edit', edit_pr_video_path(pr_video) %></td>
        <td><%= link_to 'Destroy', pr_video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pr video', new_pr_video_path %>

toruuu/app/views/pr_videos/new.html.erb
<h1>New pr_video</h1>

<%= render 'form' %>

<%= link_to 'Back', pr_videos_path %>

toruuu/app/views/pr_videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pr_video.title %>
</p>

<p>
  <strong>Video:</strong>
</p>
<p>
  <%= link_to @pr_video.video_url.to_s do %>
      <%= image_tag(@pr_video.video_url(:screenshot).to_s, id: "video", :alt => "screenshot") %>
  <% end %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pr_video.description %>
</p>

<%= link_to 'Edit', edit_pr_video_path(@pr_video) %> |
<%= link_to 'Back', pr_videos_path %>